### ISSUE TITLE
--help doesn't work from command line

### ISSUE THREAD

**Issue by aflat** [yousseb/meld#15]
Not a huge issue at all, just something I noticed. When running meld --help I get

```
Traceback (most recent call last):
  File "meld/meldapp.pyc", line 78, in do_command_line
  File "meld/meldapp.pyc", line 336, in parse_args
  File "meld/meldapp.pyc", line 155, in open_files
  File "meld/meldwindow.pyc", line 795, in open_paths
  File "meld/meldwindow.pyc", line 754, in append_vcview
  File "meld/vcview.pyc", line 298, in set_location
  File "meld/vcview.pyc", line 256, in populate_vcs_for_location
  File "meld/vc/git.pyc", line 275, in valid_repo
  File "meld/vc/_vc.pyc", line 377, in call
  File "subprocess.pyc", line 522, in call
  File "subprocess.pyc", line 710, in __init__
  File "subprocess.pyc", line 1335, in _execute_child
OSError: [Errno 2] No such file or directory: '/Volumes/<my_current_dir>/--help'
```

**Comment by aflat** [comment]
Checked your latest 8584d37f82f6b795ab932f661cb68734bf846227, that fixed it

**Comment by yousseb** [comment]
Try this: https://github.com/yousseb/meld/releases/tag/osx-8

**Comment by aflat** [comment]
that works, thanks
