### ISSUE TITLE
/Users/yousseb/ hardcoded?

### ISSUE THREAD

**Issue by GordonGustafson** [yousseb/meld#48]
I downloaded the "latest dmg" from here: https://yousseb.github.io/meld/ , then ran the following:

```
~$ /Applications/Meld.app/Contents/MacOS/Meld-bin --version

** (process:49122): WARNING **: Failed to load shared library '/Users/yousseb/gtk/inst/lib/libglib-2.0.0.dylib' referenced by the typelib: dlopen(/Users/yousseb/gtk/inst/lib/libglib-2.0.0.dylib, 9): image not found

** (process:49122): WARNING **: Failed to load shared library '/Users/yousseb/gtk/inst/lib/libgobject-2.0.0.dylib' referenced by the typelib: dlopen(/Users/yousseb/gtk/inst/lib/libgobject-2.0.0.dylib, 9): image not found
Traceback (most recent call last):
  File "/Applications/Meld.app/Contents/Resources/__boot__.py", line 316, in <module>
    _run()
  File "/Applications/Meld.app/Contents/Resources/__boot__.py", line 311, in _run
    exec(compile(source, path, 'exec'), globals(), globals())
  File "/Applications/Meld.app/Contents/Resources/meld", line 263, in <module>
    check_requirements()
  File "/Applications/Meld.app/Contents/Resources/meld", line 166, in check_requirements
    from gi.repository import Gtk
  File "/Applications/Meld.app/Contents/Resources/lib/python2.7/gi/importer.py", line 159, in load_module
    dynamic_module = load_overrides(introspection_module)
  File "/Applications/Meld.app/Contents/Resources/lib/python2.7/gi/overrides/__init__.py", line 111, in load_overrides
    override_mod = importlib.import_module('gi.overrides.' + namespace)
  File "importlib/__init__.pyc", line 37, in import_module
  File "/Applications/Meld.app/Contents/Resources/lib/python2.7/gi/overrides/Gtk.py", line 26, in <module>
    from gi.repository import GObject
  File "/Applications/Meld.app/Contents/Resources/lib/python2.7/gi/importer.py", line 159, in load_module
    dynamic_module = load_overrides(introspection_module)
  File "/Applications/Meld.app/Contents/Resources/lib/python2.7/gi/overrides/__init__.py", line 111, in load_overrides
    override_mod = importlib.import_module('gi.overrides.' + namespace)
  File "importlib/__init__.pyc", line 37, in import_module
  File "/Applications/Meld.app/Contents/Resources/lib/python2.7/gi/overrides/GObject.py", line 31, in <module>
    from gi.repository import GLib
  File "/Applications/Meld.app/Contents/Resources/lib/python2.7/gi/importer.py", line 159, in load_module
    dynamic_module = load_overrides(introspection_module)
  File "/Applications/Meld.app/Contents/Resources/lib/python2.7/gi/overrides/__init__.py", line 111, in load_overrides
    override_mod = importlib.import_module('gi.overrides.' + namespace)
  File "importlib/__init__.pyc", line 37, in import_module
  File "/Applications/Meld.app/Contents/Resources/lib/python2.7/gi/overrides/GLib.py", line 36, in <module>
    from gi import _option as option
  File "/Applications/Meld.app/Contents/Resources/lib/python2.7/gi/_option.py", line 47, in <module>
    OPTION_CONTEXT_ERROR_QUARK = GLib.quark_to_string(GLib.option_error_quark())
gi._error.GError: g-invoke-error-quark: Could not locate g_option_error_quark: dlopen(/Users/yousseb/gtk/inst/lib/libgobject-2.0.0.dylib, 9): image not found (1)
2017-08-23 11:21:34.936 Meld-bin[49122:2826146] Meld Error
~$ 
```

Why is the `/Users/yousseb/` directory appearing in the output?

**Comment by fahrinh** [comment]
I got same error
Please fix this

**Comment by yousseb** [comment]
Meld-bin should not be called directly. You should be calling Meld instead. :)

**Comment by yousseb** [comment]
Meld-bin should not be called. You can either call Meld or set the `DYLD_LIBRARY_PATH` to point to the `Frameworks` and the `Resources/lib` folders (separated by a `:`) and then call Meld-bin
