### ISSUE TITLE
3.21.0.r1 doesn't work for three way command line auto-merge

### ISSUE THREAD

**Issue by dsbecker** [yousseb/meld#97]
```
$ meld "a.txt" "b.txt" 
/Applications/Meld.3.21.0.r1.app/Contents/Resources/lib/python36.zip/meld/meldapp.py:192: Warning: invalid cast from 'GtkMenuBar' to 'GtkWindow'
```
```
$ meld --auto-merge "a.txt" "b.txt" "c.txt" --output="d.txt"
Traceback (most recent call last):
  File "/Applications/Meld.3.21.0.r1.app/Contents/Resources/lib/python3.6/gi/_gtktemplate.py", line 95, in <lambda>
    lambda s: init_template(s, cls, base_init_template)
  File "/Applications/Meld.3.21.0.r1.app/Contents/Resources/lib/python3.6/gi/_gtktemplate.py", line 106, in init_template
    "Inheritance from classes with @Gtk.Template decorators "
TypeError: Inheritance from classes with @Gtk.Template decorators is not allowed at this time
Traceback (most recent call last):
  File "/Applications/Meld.3.21.0.r1.app/Contents/Resources/lib/python3.6/gi/_gtktemplate.py", line 95, in <lambda>
    lambda s: init_template(s, cls, base_init_template)
  File "/Applications/Meld.3.21.0.r1.app/Contents/Resources/lib/python3.6/gi/_gtktemplate.py", line 106, in init_template
    "Inheritance from classes with @Gtk.Template decorators "
TypeError: Inheritance from classes with @Gtk.Template decorators is not allowed at this time
Traceback (most recent call last):
  File "meld/meldapp.pyc", line 87, in do_command_line
  File "meld/meldapp.pyc", line 404, in parse_args
  File "meld/meldapp.pyc", line 165, in open_files
  File "meld/meldwindow.pyc", line 483, in open_paths
  File "meld/meldwindow.pyc", line 429, in append_diff
  File "meld/meldwindow.pyc", line 406, in append_filemerge
  File "meld/filediff.pyc", line 249, in __init__
  File "meld/filediff.pyc", line 249, in <listcomp>
AttributeError: 'Child' object has no attribute 'get_buffer'
```

**Comment by saurabh-cimpress** [comment]
+1

**Comment by ssalexa** [comment]
+1 here

**Comment by yousseb** [comment]
@kaiw This one's for you.. :) 
This looks like an upstream issue with current master. I've synced up to latest master and it still happens.

**Comment by kaiw** [comment]
Yep, this isn't great. I have a plan to address this, but unfortunately it's a little disruptive, so I might need to think about it for a bit.

**Comment by dsbecker** [comment]
In the mean time, can this fork roll back to a prior upstream? Or is it not worth it? This is a beta build after all.

**Comment by kaiw** [comment]
This should be fixed with https://github.com/GNOME/meld/commit/d926caa0562acaafb2afffa5f0cad149017fec82. However, I don't use this mode personally, so I may have missed some things.

**Comment by yousseb** [comment]
@dsbecker could you please verify that this has been fixed in r3?

**Comment by dsbecker** [comment]
I will test this on Monday when I’m back on the job. Thank you for all your hard work!

**Comment by dsbecker** [comment]
Confirmed, this works now. Closing...
